<script type="text/javascript" src="../js/loadingScreen.js"></script>
<script type="text/javascript" src="../js/navResponsive.js"></script>
<script type="text/javascript" src="../js/navDropdown.js"></script>
<script type="text/javascript" src="../js/searchOrtSelect.js"></script>
<script type="text/javascript" src="../js/searchAnzeigen.js"></script>
<script type="text/javascript" src="../js/searchRubriken.js"></script>
<script type="text/javascript" src="../js/searchNews.js"></script>
<script type="text/javascript" src="../js/bildAuswahlForm.js"></script>
<script type="text/javascript" src="../js/swipeDetectorIndexPHP.js"></script>
<script type="text/javascript" src="../js/newsCountStrings.js"></script>
<script type="text/javascript" src="../js/anzeigenCheckboxMax.js"></script>
<script type="text/javascript" src="../js/loginAndRegister.js"></script>
<script type="text/javascript" src="../js/rubrikenChange.js"></script>
<script type="text/javascript" src="../js/AdminAreaCollapse.js"></script>
